// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2y6Ubnb4rKM_QKl-tLNoFRjQo_y9omec',
    appId: '1:555511570718:web:46a2cf254aa6c5e428a90f',
    messagingSenderId: '555511570718',
    projectId: 'pdmchat-4ff4c',
    authDomain: 'pdmchat-4ff4c.firebaseapp.com',
    databaseURL: 'https://pdmchat-4ff4c-default-rtdb.firebaseio.com',
    storageBucket: 'pdmchat-4ff4c.appspot.com',
    measurementId: 'G-Z78B68D4WQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB1Zfm3z5IuXR1ttPNjS48QuACxdspBnA',
    appId: '1:555511570718:android:471038a9f136b6c828a90f',
    messagingSenderId: '555511570718',
    projectId: 'pdmchat-4ff4c',
    databaseURL: 'https://pdmchat-4ff4c-default-rtdb.firebaseio.com',
    storageBucket: 'pdmchat-4ff4c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJK2hGqAKoBu3xtKAzk3cTn82h4tLBmL0',
    appId: '1:555511570718:ios:ef706710553b5edc28a90f',
    messagingSenderId: '555511570718',
    projectId: 'pdmchat-4ff4c',
    databaseURL: 'https://pdmchat-4ff4c-default-rtdb.firebaseio.com',
    storageBucket: 'pdmchat-4ff4c.appspot.com',
    iosBundleId: 'com.example.pdmChat',
  );
}
